export const metadata = {
  title: 'Terms & Conditions | Career Compass',
};

export default function TermsPage() {
  return (
    <div className="max-w-7xl mx-auto px-6 py-8">
      {/* Page Header (same pattern as dashboard) */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-slate-100 mb-2">
          Terms & Conditions
        </h1>
        <p className="text-sm text-slate-600 dark:text-slate-400">
          Last updated: {new Date().toLocaleDateString()}
        </p>
      </div>

      {/* Card container (same as dashboard cards) */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-8">
        <section className="space-y-6 text-slate-700 dark:text-slate-300 leading-relaxed">
          <p>
            Welcome to Career Compass. By accessing or using this application,
            you agree to be bound by these Terms and Conditions.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100">
            Use of the Service
          </h2>
          <p>
            Career Compass provides AI-powered resume analysis and career
            guidance. The information provided is for informational purposes
            only and should not be considered professional advice.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100">
            User Responsibilities
          </h2>
          <p>
            You agree not to misuse the service, attempt unauthorized access, or
            use the platform for unlawful activities.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100">
            Limitation of Liability
          </h2>
          <p>
            Career Compass is not responsible for decisions made based on the
            information generated by the platform.
          </p>

          <h2 className="text-xl font-semibold text-slate-900 dark:text-slate-100">
            Changes
          </h2>
          <p>
            We reserve the right to modify these terms at any time. Continued use
            of the service implies acceptance of updated terms.
          </p>
        </section>
      </div>
    </div>
  );
}
